### ISSUE TITLE
Free Memory Gauge is not visually correct

### ISSUE THREAD

**Issue by mstaalesen** [bergquist/dashboards#1]
Great idea for a dashboard - hope some constructive feedback is ok!

The way the Gauge for Memory is shown now (with Memory Free), it will be in the Red if 100% memory is free. At least in my case, this is a good thing. On one of my servers, it was green with 2% free memory. 

Suggest that you change it to memory used, perhaps with something similar to this:

`((node_memory_MemTotal{instance=~"$server"} - node_memory_MemFree{instance=~"$server"}) / node_memory_MemTotal{instance=~"$server"}) * 100`

**Comment by MrMMorris** [comment]
it also would probably make sense to have the `Free Memory` graph use `node_memory_MemAvailable` as I believe it is a more accurate representation of the real amount of usable memory (taking cache/buffer into account). Correct me if I'm wrong 😄

**Comment by bergquist** [comment]
Thames for the feedback! Ill try to fix this as soon as I'm done traveling :)

**Comment by mstaalesen** [comment]
@MrMMorris AFAIK node_memory_MemAvailable is not available (no pun intended) out of the box?

**Comment by MrMMorris** [comment]
node exporter 0.12.0 seems to have it ¯\_(ツ)_/¯

**Comment by philicious** [comment]
I noticed the same. 
However I do like the graph to be "free mem" and not "mem used" so I changed the gauge to visually make more sense:
inverted the color scheme so its red to green and also set the threshold to 20 (%)

**Comment by MrMMorris** [comment]
@philicious that's exactly what I did. I would have submitted a PR, but didn't have time to diff the json config.

**Comment by bergquist** [comment]
I've updated the dashboard. Any feedback is welcome :)

**Comment by philicious** [comment]
@MrMMorris @bergquist I do have 

```
node_exporter, version 0.12.0 (branch: master, revision: df8dcd2)
  build user:       root@ff68505a5469
  build date:       20160505-22:14:18
  go version:       go1.6.2
```

however I dont have `node_memory_MemAvailable` 

what is your version?

**Comment by philicious** [comment]
btw if MemAvailable isnt available (haha) .. the correct query would be for the graph `node_memory_MemFree{instance=~"$server"}+node_memory_Buffers{instance=~"$server"}+node_memory_Cached{instance=~"$server"}`
and for the gauge it would be `((node_memory_MemFree{instance=~"$server"}+node_memory_Buffers{instance=~"$server"}+node_memory_Cached{instance=~"$server"})/ node_memory_MemTotal{instance=~"$server"}) * 100`

this give a much more accurate view of the memory usage. or how much can be expected available.
