### ISSUE TITLE
Is idle cpu really showing Cpu usage in %?

### ISSUE THREAD

**Issue by mstaalesen** [bergquist/dashboards#2]
Just a quick question if you don't mind.

Looking at the metrics documentation:

> # HELP node_cpu Seconds the cpus spent in each mode.

You are using node_cpu idle-time, is this really the cpu usage in % with how you are calculating it? I thought it was much tougher than that to get actual cpu usage on a server?

**Comment by bergquist** [comment]
@mstaalesen the query is based on this blogpost http://www.robustperception.io/understanding-machine-cpu-usage/

**Comment by mstaalesen** [comment]
Sorry, I was mixing it up with attempting to show cpu per application in linux. Closing.
